### ISSUE TITLE
Some bugs needs to be fixed 

### ISSUE THREAD

**Issue by TheAz928** [BlockHorizons/FactionsPE#5]
Block place:

When placing blocks it should not let strangers place any blocks to claimed land, it only happens when stranger standing on claimed land, but he can place from far.

FactionHome:
/f home sets properly but in restart or reload, it unset

More:
If I find out more I'll post it here

**Comment by Kris-Driv** [comment]
Both bugs are fixed in 0.9.8.6. Thanks

**Comment by TheAz928** [comment]
@Chris-Prime /f home still doesn't save if server stops or restarts

**Comment by Kris-Driv** [comment]
@TheAz928 that's weird. I'll take a deeper look into it. It's running on my server for 4 months and no one has reported this issue and I've tested it a gazillion times.

**Comment by TheAz928** [comment]
@Cris-Prime weird thing tho

**Comment by Thunder33345** [comment]
listing how you reproduce it with a server that only has a single plugin should explain more of this maybe

**Comment by Kris-Driv** [comment]
What data provider plugin was using?

**Comment by TheAz928** [comment]
Yaml

**Comment by Kris-Driv** [comment]
Ok. I'll test it out. Anything else I should consider?

**Comment by Kris-Driv** [comment]
I can not reproduce this issue.
